"""Initial tables

Revision ID: 727c5130c0a8
Revises:
Create Date: 2026-02-19 11:15:39.165651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '727c5130c0a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic',
    sa.Column('symbol', sa.String(), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(), nullable=True, comment='股票名称'),
    sa.Column('industry', sa.String(), nullable=True, comment='所属行业'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_basic_name'), 'stock_basic', ['name'], unique=False)
    op.create_index(op.f('ix_stock_basic_symbol'), 'stock_basic', ['symbol'], unique=False)
    op.create_index('ix_stock_basic_symbol_name', 'stock_basic', ['symbol', 'name'], unique=False)
    op.create_table('strategy_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_code', sa.String(), nullable=False, comment='策略代码'),
    sa.Column('strategy_name', sa.String(), nullable=False, comment='策略名称'),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='策略参数'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_config_id'), 'strategy_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_config_id'), table_name='strategy_config')
    op.drop_table('strategy_config')
    op.drop_index('ix_stock_basic_symbol_name', table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_symbol'), table_name='stock_basic')
    op.drop_index(op.f('ix_stock_basic_name'), table_name='stock_basic')
    op.drop_table('stock_basic')
    # ### end Alembic commands ###
